# Create a workflow that runs on mac builds and uploads an ipa from my tauri app on every push

name: Build
on: [push, pull_request]

jobs:
  test:
    name: Build iOS (.ipa)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i
      - run: bun run tauri ios build
        # continue on error
        continue-on-error: true
      #   - run: bun run build
      - name: Build Xcode Project
        run: xcodebuild -scheme shrinkwrap_iOS -workspace /Users/runner/work/shrinkwrap/shrinkwrap/src-tauri/gen/apple/shrinkwrap.xcodeproj/project.xcworkspace/ -sdk iphoneos -configuration release archive -archivePath ./archive CODE_SIGNING_REQUIRED=NO AD_HOC_CODE_SIGNING_ALLOWED=YES CODE_SIGNING_ALLOWED=NO ORG_IDENTIFIER=me.nabdev IDEPackageSupportUseBuiltinSCM=YES SDKROOT=iphoneos18.0
      - run: mkdir Payload
      - run: mkdir Payload/shrinkwrap.app
      - run: cp -R archive.xcarchive/Products/Applications/shrinkwrap.app/ Payload/shrinkwrap.app/
      - run: zip -r shrinkwrap.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: shrinkwrap.ipa
