# Create a workflow that runs on mac builds and uploads an ipa from my tauri app on every push

name: Build
on: [push, pull_request]

jobs:
  test:
    name: Deploy to TestFlight
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun i
      - name: Build iOS
        run: bun run tauri ios build --export-method app-store-connect
      - name: Upload to TestFlight
        run: xcrun altool --upload-app --type ios --file "./src-tauri/gen/apple/build/arm64/shrinkwrap.ipa" --apiKey ${{ secrets.APPLE_API_KEY_ID }} --apiIssuer ${{ secrets.APPLE_API_ISSUER }}
      - name: Upload iOS artifact
        uses: actions/upload-artifact@v4
        with:
          path: src-tauri/gen/apple/build/arm64/shrinkwrap.ipa
